//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoLux.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErgoLux.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by {0}.
        /// </summary>
        internal static string strAboutCompanyName {
            get {
                return ResourceManager.GetString("strAboutCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright {0}.
        /// </summary>
        internal static string strAboutCopyright {
            get {
                return ResourceManager.GetString("strAboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergonomics measurement software tool for Konica Minolta&apos;s illuminance-meter T-10A.
        ///
        ///No commercial use allowed whatsoever. Contact the author for any inquiries.
        ///
        ///If you find this software useful, please consider supporting it!.
        /// </summary>
        internal static string strAboutDescription {
            get {
                return ResourceManager.GetString("strAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name: {0}.
        /// </summary>
        internal static string strAboutProductName {
            get {
                return ResourceManager.GetString("strAboutProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string strAboutVersion {
            get {
                return ResourceManager.GetString("strAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string strBtnAccept {
            get {
                return ResourceManager.GetString("strBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string strBtnCancel {
            get {
                return ResourceManager.GetString("strBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data.
        /// </summary>
        internal static string strBtnData {
            get {
                return ResourceManager.GetString("strBtnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string strBtnExport {
            get {
                return ResourceManager.GetString("strBtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string strBtnReset {
            get {
                return ResourceManager.GetString("strBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string strBtnSettings {
            get {
                return ResourceManager.GetString("strBtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plots&apos; crosshair.
        /// </summary>
        internal static string strChkCrossHair {
            get {
                return ResourceManager.GetString("strChkCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative fractal dimension.
        /// </summary>
        internal static string strChkCumulative {
            get {
                return ResourceManager.GetString("strChkCumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember open/save dialog previous path.
        /// </summary>
        internal static string strChkDlgPath {
            get {
                return ResourceManager.GetString("strChkDlgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy (approximate &amp;&amp; sample).
        /// </summary>
        internal static string strChkEntropy {
            get {
                return ResourceManager.GetString("strChkEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot average.
        /// </summary>
        internal static string strChkPlotAverage {
            get {
                return ResourceManager.GetString("strChkPlotAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot distribution.
        /// </summary>
        internal static string strChkPlotDistribution {
            get {
                return ResourceManager.GetString("strChkPlotDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot ratios.
        /// </summary>
        internal static string strChkPlotRatios {
            get {
                return ResourceManager.GetString("strChkPlotRatios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot raw data.
        /// </summary>
        internal static string strChkPlotRaw {
            get {
                return ResourceManager.GetString("strChkPlotRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (dB).
        /// </summary>
        internal static string strChkPower {
            get {
                return ResourceManager.GetString("strChkPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all fields
        ///to their default values?.
        /// </summary>
        internal static string strDlgReset {
            get {
                return ResourceManager.GetString("strDlgReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings?.
        /// </summary>
        internal static string strDlgResetTitle {
            get {
                return ResourceManager.GetString("strDlgResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings file.
        ///
        ///{0}
        ///
        ///Default values will be used instead..
        /// </summary>
        internal static string strErrorDeserialize {
            get {
                return ResourceManager.GetString("strErrorDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strErrorDeserializeTitle {
            get {
                return ResourceManager.GetString("strErrorDeserializeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoLux data.
        /// </summary>
        internal static string strFileHeader01 {
            get {
                return ResourceManager.GetString("strFileHeader01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string strFileHeader02 {
            get {
                return ResourceManager.GetString("strFileHeader02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string strFileHeader03 {
            get {
                return ResourceManager.GetString("strFileHeader03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total measuring time.
        /// </summary>
        internal static string strFileHeader04 {
            get {
                return ResourceManager.GetString("strFileHeader04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sensors.
        /// </summary>
        internal static string strFileHeader05 {
            get {
                return ResourceManager.GetString("strFileHeader05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data points.
        /// </summary>
        internal static string strFileHeader06 {
            get {
                return ResourceManager.GetString("strFileHeader06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling frequency.
        /// </summary>
        internal static string strFileHeader07 {
            get {
                return ResourceManager.GetString("strFileHeader07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor #.
        /// </summary>
        internal static string strFileHeader08 {
            get {
                return ResourceManager.GetString("strFileHeader08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string strFileHeader09 {
            get {
                return ResourceManager.GetString("strFileHeader09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string strFileHeader10 {
            get {
                return ResourceManager.GetString("strFileHeader10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string strFileHeader11 {
            get {
                return ResourceManager.GetString("strFileHeader11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Average.
        /// </summary>
        internal static string strFileHeader12 {
            get {
                return ResourceManager.GetString("strFileHeader12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max.
        /// </summary>
        internal static string strFileHeader13 {
            get {
                return ResourceManager.GetString("strFileHeader13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average/Max.
        /// </summary>
        internal static string strFileHeader14 {
            get {
                return ResourceManager.GetString("strFileHeader14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string strFileHeader15 {
            get {
                return ResourceManager.GetString("strFileHeader15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance.
        /// </summary>
        internal static string strFileHeader16 {
            get {
                return ResourceManager.GetString("strFileHeader16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an empty line..
        /// </summary>
        internal static string strFileHeader17 {
            get {
                return ResourceManager.GetString("strFileHeader17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing column headers (series names)..
        /// </summary>
        internal static string strFileHeader18 {
            get {
                return ResourceManager.GetString("strFileHeader18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string strFileHeader19 {
            get {
                return ResourceManager.GetString("strFileHeader19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string strFileHeader20 {
            get {
                return ResourceManager.GetString("strFileHeader20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string strFileHeader21 {
            get {
                return ResourceManager.GetString("strFileHeader21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string strFileHeader22 {
            get {
                return ResourceManager.GetString("strFileHeader22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string strFileHeader23 {
            get {
                return ResourceManager.GetString("strFileHeader23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string strFileHeader24 {
            get {
                return ResourceManager.GetString("strFileHeader24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string strFileHeaderColon {
            get {
                return ResourceManager.GetString("strFileHeaderColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;{0}&apos; is mis-formatted..
        /// </summary>
        internal static string strFileHeaderSection {
            get {
                return ResourceManager.GetString("strFileHeaderSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoLux.
        /// </summary>
        internal static string strFormTitle {
            get {
                return ResourceManager.GetString("strFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strFrmLanguage {
            get {
                return ResourceManager.GetString("strFrmLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strFrmSettings {
            get {
                return ResourceManager.GetString("strFrmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal analysis.
        /// </summary>
        internal static string strFrmTitle {
            get {
                return ResourceManager.GetString("strFrmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string strFrmTitleUnion {
            get {
                return ResourceManager.GetString("strFrmTitleUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string strGridDescription {
            get {
                return ResourceManager.GetString("strGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device location.
        /// </summary>
        internal static string strGridDevice {
            get {
                return ResourceManager.GetString("strGridDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string strGridFlags {
            get {
                return ResourceManager.GetString("strGridFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string strGridID {
            get {
                return ResourceManager.GetString("strGridID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location ID.
        /// </summary>
        internal static string strGridLocation {
            get {
                return ResourceManager.GetString("strGridLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string strGridSerial {
            get {
                return ResourceManager.GetString("strGridSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string strGridType {
            get {
                return ResourceManager.GetString("strGridType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abscissa axis.
        /// </summary>
        internal static string strGrpAxis {
            get {
                return ResourceManager.GetString("strGrpAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI and data format.
        /// </summary>
        internal static string strGrpCulture {
            get {
                return ResourceManager.GetString("strGrpCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot distribution.
        /// </summary>
        internal static string strGrpPlot {
            get {
                return ResourceManager.GetString("strGrpPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array minimum points.
        /// </summary>
        internal static string strLblArrayPoints {
            get {
                return ResourceManager.GetString("strLblArrayPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        internal static string strLblBaudRate {
            get {
                return ResourceManager.GetString("strLblBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-file path.
        /// </summary>
        internal static string strLblData {
            get {
                return ResourceManager.GetString("strLblData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data bits.
        /// </summary>
        internal static string strLblDataBits {
            get {
                return ResourceManager.GetString("strLblDataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric data-formatting string.
        /// </summary>
        internal static string strLblDataFormat {
            get {
                return ResourceManager.GetString("strLblDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTDI device list.
        /// </summary>
        internal static string strLblDeviceList {
            get {
                return ResourceManager.GetString("strLblDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index end.
        /// </summary>
        internal static string strLblEnd {
            get {
                return ResourceManager.GetString("strLblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow control.
        /// </summary>
        internal static string strLblFlow {
            get {
                return ResourceManager.GetString("strLblFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        internal static string strLblFrequency {
            get {
                return ResourceManager.GetString("strLblFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string strLblOff {
            get {
                return ResourceManager.GetString("strLblOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string strLblOn {
            get {
                return ResourceManager.GetString("strLblOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        internal static string strLblParity {
            get {
                return ResourceManager.GetString("strLblParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot window (seconds).
        /// </summary>
        internal static string strLblPlotWindow {
            get {
                return ResourceManager.GetString("strLblPlotWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sensors.
        /// </summary>
        internal static string strLblSensors {
            get {
                return ResourceManager.GetString("strLblSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select series.
        /// </summary>
        internal static string strLblSeries {
            get {
                return ResourceManager.GetString("strLblSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index start.
        /// </summary>
        internal static string strLblStart {
            get {
                return ResourceManager.GetString("strLblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop bits.
        /// </summary>
        internal static string strLblStopBits {
            get {
                return ResourceManager.GetString("strLblStopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string strLblWindow {
            get {
                return ResourceManager.GetString("strLblWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string strMenuMainFile {
            get {
                return ResourceManager.GetString("strMenuMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit....
        /// </summary>
        internal static string strMenuMainFileExit {
            get {
                return ResourceManager.GetString("strMenuMainFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string strMenuMainFileOpen {
            get {
                return ResourceManager.GetString("strMenuMainFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save....
        /// </summary>
        internal static string strMenuMainFileSave {
            get {
                return ResourceManager.GetString("strMenuMainFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string strMenuMainHelpAbout {
            get {
                return ResourceManager.GetString("strMenuMainHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string strMenuMainHelpText {
            get {
                return ResourceManager.GetString("strMenuMainHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string strMenuMainTools {
            get {
                return ResourceManager.GetString("strMenuMainTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connect.
        /// </summary>
        internal static string strMenuMainToolsConnect {
            get {
                return ResourceManager.GetString("strMenuMainToolsConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disconnect.
        /// </summary>
        internal static string strMenuMainToolsDisconnect {
            get {
                return ResourceManager.GetString("strMenuMainToolsDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings....
        /// </summary>
        internal static string strMenuMainToolsSettings {
            get {
                return ResourceManager.GetString("strMenuMainToolsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string strMenuMainView {
            get {
                return ResourceManager.GetString("strMenuMainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averages.
        /// </summary>
        internal static string strMenuMainViewAverage {
            get {
                return ResourceManager.GetString("strMenuMainViewAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial distribution.
        /// </summary>
        internal static string strMenuMainViewDistribution {
            get {
                return ResourceManager.GetString("strMenuMainViewDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu.
        /// </summary>
        internal static string strMenuMainViewMenu {
            get {
                return ResourceManager.GetString("strMenuMainViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratios.
        /// </summary>
        internal static string strMenuMainViewRatio {
            get {
                return ResourceManager.GetString("strMenuMainViewRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw data.
        /// </summary>
        internal static string strMenuMainViewRaw {
            get {
                return ResourceManager.GetString("strMenuMainViewRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toolbar.
        /// </summary>
        internal static string strMenuMainViewToolbar {
            get {
                return ResourceManager.GetString("strMenuMainViewToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set data characteristics
        ///(data bits, stop bits, and parity).
        ///Error:
        ///{0}.
        /// </summary>
        internal static string strMsbBoxErrorBits {
            get {
                return ResourceManager.GetString("strMsbBoxErrorBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set Baud rate.
        ///Error:
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorBaudRate {
            get {
                return ResourceManager.GetString("strMsgBoxErrorBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate error.
        /// </summary>
        internal static string strMsgBoxErrorBaudRateTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorBaudRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits error.
        /// </summary>
        internal static string strMsgBoxErrorBitsTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorBitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is closed. Please, go to
        ///&apos;Settings&apos; to open the device..
        /// </summary>
        internal static string strMsgBoxErrorDeviceClosed {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDeviceClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device error.
        /// </summary>
        internal static string strMsgBoxErrorDeviceClosedTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDeviceClosedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load FTD2XX.DLL. Are the FTDI drivers installed?.
        /// </summary>
        internal static string strMsgBoxErrorDrivers {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading drivers.
        /// </summary>
        internal static string strMsgBoxErrorDriversTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDriversTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set flow control.
        ///Error:
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorFlowControl {
            get {
                return ResourceManager.GetString("strMsgBoxErrorFlowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow control error.
        /// </summary>
        internal static string strMsgBoxErrorFlowControlTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorFlowControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to load FTD2XX.DLL from:.
        /// </summary>
        internal static string strMsgBoxErrorLoading {
            get {
                return ResourceManager.GetString("strMsgBoxErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading DLL.
        /// </summary>
        internal static string strMsgBoxErrorLoadingTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorLoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error happened while opening data file.
        ///Please try again later or contact the software engineer.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorOpenData {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening data.
        /// </summary>
        internal static string strMsgBoxErrorOpenDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpenDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the device.
        /// </summary>
        internal static string strMsgBoxErrorOpenDevice {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpenDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strMsgBoxErrorOpenDeviceTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpenDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open device.
        ///Error:
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorOpening {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening device.
        /// </summary>
        internal static string strMsgBoxErrorOpeningTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpeningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error happened while saving data to disk.
        ///Please try again later or contact the software engineer.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorSaveData {
            get {
                return ResourceManager.GetString("strMsgBoxErrorSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data.
        /// </summary>
        internal static string strMsgBoxErrorSaveDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorSaveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings file.
        ///
        ///{0}
        ///
        ///Default values will be used instead..
        /// </summary>
        internal static string strMsgBoxErrorSettings {
            get {
                return ResourceManager.GetString("strMsgBoxErrorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strMsgBoxErrorSettingsTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set timeouts.
        ///Error:
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorTimeouts {
            get {
                return ResourceManager.GetString("strMsgBoxErrorTimeouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeouts error.
        /// </summary>
        internal static string strMsgBoxErrorTimeoutsTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorTimeoutsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit
        ///the application?.
        /// </summary>
        internal static string strMsgBoxExit {
            get {
                return ResourceManager.GetString("strMsgBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string strMsgBoxExitTitle {
            get {
                return ResourceManager.GetString("strMsgBoxExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data available to be saved..
        /// </summary>
        internal static string strMsgBoxNoData {
            get {
                return ResourceManager.GetString("strMsgBoxNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string strMsgBoxNoDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxNoDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all fields
        ///to their default values?.
        /// </summary>
        internal static string strMsgBoxReset {
            get {
                return ResourceManager.GetString("strMsgBoxReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset?.
        /// </summary>
        internal static string strMsgBoxResetTitle {
            get {
                return ResourceManager.GetString("strMsgBoxResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully saved to disk..
        /// </summary>
        internal static string strMsgBoxSaveData {
            get {
                return ResourceManager.GetString("strMsgBoxSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saving.
        /// </summary>
        internal static string strMsgBoxSaveDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxSaveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation of the Hausdorff-Besicovitch fractal
        ///dimension has been stopped..
        /// </summary>
        internal static string strMsgBoxTaskCancel {
            get {
                return ResourceManager.GetString("strMsgBoxTaskCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string strMsgBoxTaskCancelTitle {
            get {
                return ResourceManager.GetString("strMsgBoxTaskCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoLux file (*.elux)|*.elux|Text file (*.txt)|*.txt|Binary file (*.bin)|*.bin|All files (*.*)|*.*.
        /// </summary>
        internal static string strOpenDlgFilter {
            get {
                return ResourceManager.GetString("strOpenDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open illuminance data.
        /// </summary>
        internal static string strOpenDlgTitle {
            get {
                return ResourceManager.GetString("strOpenDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max, average, min.
        /// </summary>
        internal static string strPlotAverageTitle {
            get {
                return ResourceManager.GetString("strPlotAverageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotAverageXLabel {
            get {
                return ResourceManager.GetString("strPlotAverageXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lux.
        /// </summary>
        internal static string strPlotAverageYLabel {
            get {
                return ResourceManager.GetString("strPlotAverageYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance distribution.
        /// </summary>
        internal static string strPlotDistributionTitle {
            get {
                return ResourceManager.GetString("strPlotDistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance ratios.
        /// </summary>
        internal static string strPlotRatiosTitle {
            get {
                return ResourceManager.GetString("strPlotRatiosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotRatiosXLabel {
            get {
                return ResourceManager.GetString("strPlotRatiosXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string strPlotRatiosYLabel {
            get {
                return ResourceManager.GetString("strPlotRatiosYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance.
        /// </summary>
        internal static string strPlotRawTitle {
            get {
                return ResourceManager.GetString("strPlotRawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotRawXLabel {
            get {
                return ResourceManager.GetString("strPlotRawXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lux.
        /// </summary>
        internal static string strPlotRawYLabel {
            get {
                return ResourceManager.GetString("strPlotRawYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture formatting.
        /// </summary>
        internal static string strRadCurrentCulture {
            get {
                return ResourceManager.GetString("strRadCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant culture formatting.
        /// </summary>
        internal static string strRadInvariantCulture {
            get {
                return ResourceManager.GetString("strRadInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        internal static string strRadRadar {
            get {
                return ResourceManager.GetString("strRadRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial gauge.
        /// </summary>
        internal static string strRadRadialGauge {
            get {
                return ResourceManager.GetString("strRadRadialGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strRadUserCulture {
            get {
                return ResourceManager.GetString("strRadUserCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from file.
        ///{0}.
        /// </summary>
        internal static string strReadDataError {
            get {
                return ResourceManager.GetString("strReadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The culture identifier string name is not valid.
        ///{0}.
        /// </summary>
        internal static string strReadDataErrorCulture {
            get {
                return ResourceManager.GetString("strReadDataErrorCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture name error.
        /// </summary>
        internal static string strReadDataErrorCultureTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorCultureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric value: {0}.
        /// </summary>
        internal static string strReadDataErrorNumber {
            get {
                return ResourceManager.GetString("strReadDataErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing data.
        /// </summary>
        internal static string strReadDataErrorNumberTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening data.
        /// </summary>
        internal static string strReadDataErrorTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoLux file (*.elux)|*.elux|Text file (*.txt)|*.txt|Binary file (*.bin)|*.bin|All files (*.*)|*.*.
        /// </summary>
        internal static string strSaveDlgFilter {
            get {
                return ResourceManager.GetString("strSaveDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save illuminance data.
        /// </summary>
        internal static string strSaveDlgTitle {
            get {
                return ResourceManager.GetString("strSaveDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving data.
        /// </summary>
        internal static string strStatusExchange {
            get {
                return ResourceManager.GetString("strStatusExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string strStatusID {
            get {
                return ResourceManager.GetString("strStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location ID.
        /// </summary>
        internal static string strStatusLocation {
            get {
                return ResourceManager.GetString("strStatusLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string strStatusOpen {
            get {
                return ResourceManager.GetString("strStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plot&apos;s crosshair mode.
        /// </summary>
        internal static string strStatusTipCrossHair {
            get {
                return ResourceManager.GetString("strStatusTipCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot distribution.
        /// </summary>
        internal static string strStatusTipDistribution {
            get {
                return ResourceManager.GetString("strStatusTipDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange status.
        /// </summary>
        internal static string strStatusTipExchange {
            get {
                return ResourceManager.GetString("strStatusTipExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string strStatusTipID {
            get {
                return ResourceManager.GetString("strStatusTipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-10A location ID.
        /// </summary>
        internal static string strStatusTipLocation {
            get {
                return ResourceManager.GetString("strStatusTipLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot max, average and min.
        /// </summary>
        internal static string strStatusTipMax {
            get {
                return ResourceManager.GetString("strStatusTipMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion status.
        /// </summary>
        internal static string strStatusTipOpen {
            get {
                return ResourceManager.GetString("strStatusTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot ratios.
        /// </summary>
        internal static string strStatusTipRatio {
            get {
                return ResourceManager.GetString("strStatusTipRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot raw data.
        /// </summary>
        internal static string strStatusTipRaw {
            get {
                return ResourceManager.GetString("strStatusTipRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        internal static string strStatusTipType {
            get {
                return ResourceManager.GetString("strStatusTipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        internal static string strStatusType {
            get {
                return ResourceManager.GetString("strStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-10A sensor.
        /// </summary>
        internal static string strTabDevice {
            get {
                return ResourceManager.GetString("strTabDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        internal static string strTabGUI {
            get {
                return ResourceManager.GetString("strTabGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plots.
        /// </summary>
        internal static string strTabPlots {
            get {
                return ResourceManager.GetString("strTabPlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strToolStripAbout {
            get {
                return ResourceManager.GetString("strToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string strToolStripConnect {
            get {
                return ResourceManager.GetString("strToolStripConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string strToolStripDisconnect {
            get {
                return ResourceManager.GetString("strToolStripDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strToolStripExit {
            get {
                return ResourceManager.GetString("strToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string strToolStripOpen {
            get {
                return ResourceManager.GetString("strToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strToolStripSave {
            get {
                return ResourceManager.GetString("strToolStripSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strToolStripSettings {
            get {
                return ResourceManager.GetString("strToolStripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        internal static string strToolTipAbout {
            get {
                return ResourceManager.GetString("strToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start receiving data from T-10A device.
        /// </summary>
        internal static string strToolTipConnect {
            get {
                return ResourceManager.GetString("strToolTipConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop and disconnect T-10A device.
        /// </summary>
        internal static string strToolTipDisconnect {
            get {
                return ResourceManager.GetString("strToolTipDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string strToolTipExit {
            get {
                return ResourceManager.GetString("strToolTipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data file from disk.
        /// </summary>
        internal static string strToolTipOpen {
            get {
                return ResourceManager.GetString("strToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        internal static string strToolTipSave {
            get {
                return ResourceManager.GetString("strToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for plots, data, and UI.
        /// </summary>
        internal static string strToolTipSettings {
            get {
                return ResourceManager.GetString("strToolTipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language.
        /// </summary>
        internal static string strToolTipUILanguage {
            get {
                return ResourceManager.GetString("strToolTipUILanguage", resourceCulture);
            }
        }
    }
}
